### ISSUE TITLE
 Can't build due to : can't load package: package command-line-arguments

### ISSUE THREAD

**Issue by 309382570** [mitchellh/gox#106]
Can't use gox to build any project..
It show the error info below: ()
Stderr: can't load package: package command-line-arguments: cannot find package "command-line-arguments" in any of:
	/usr/local/go/src/command-line-arguments (from $GOROOT)
	/opt/wh/src/command-line-arguments (from $GOPATH)

And here is my go env and I am using Mac: 

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/opt/wh/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/c4/wc4z8_dx1cb6bq2sfrdc76540000gn/T/go-build143723401=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

**Comment by mattfarina** [comment]
@309382570 can you use `go build` on the project in question? It appears it has a missing dependency.

I just tested gox (tip of master) and it seems to be working.

**Comment by 309382570** [comment]
@mattfarina thank you for your test.
I can go build the project and get my own platform binary file and I can' t build any of my project with gox because of the same error. Never see package "command-line-arguments" before.

**Comment by mattfarina** [comment]
What version of Go are you using and how did you install it? I've not dug into this in depth but the go internal loader had special code for handling packages with this name. It appears that's not being executed.

**Comment by 309382570** [comment]
go version go1.9.2 darwin/amd64

**Comment by mattfarina** [comment]
How did you install go?

**Comment by 309382570** [comment]
Download go 1.9.2 darwin-amd64.pkg from the golang.org/dl/.
And it replace the 1.8 golang in my Mac. 
I try to remove gox and the source code in my GOPATH and use the go get again.
But it seem to have the same problem.

**Comment by mattfarina** [comment]
@309382570 the problem is not with gox. Something is wrong with your go installation. You should never get the error about "command-line-arguments" because there is special handling in go for that. You might want to try completely uninstalling go. Remove it completely. What's in the `GOROOT` and all of it. Then try reinstalling.

**Comment by 309382570** [comment]
@mattfarina   Thanks a lot !!!!   
I may find the problem.
IF I use
`$ gox -osarch="linux/amd64" ./`
instead of 
`$ gox -osarch="linux/amd64" ./main.go `
No errors orrcurred !

**Comment by CHchenf** [comment]
gox  .\hello.go
Number of parallel builds: 3

-->      darwin/386: command-line-arguments
-->    darwin/amd64: command-line-arguments
-->       linux/arm: command-line-arguments
-->       linux/386: command-line-arguments
-->     linux/amd64: command-line-arguments
-->     freebsd/386: command-line-arguments
-->   openbsd/amd64: command-line-arguments
-->     openbsd/386: command-line-arguments
-->     windows/386: command-line-arguments
-->   windows/amd64: command-line-arguments
-->     freebsd/arm: command-line-arguments
-->   freebsd/amd64: command-line-arguments
-->      netbsd/386: command-line-arguments
-->    netbsd/amd64: command-line-arguments
-->      netbsd/arm: command-line-arguments
-->     linux/s390x: command-line-arguments
-->    linux/mips64: command-line-arguments
-->  linux/mips64le: command-line-arguments
-->    linux/mipsle: command-line-arguments
-->      linux/mips: command-line-arguments

20 errors occurred:
--> darwin/amd64 error: exit status 1
Stderr: can't load package: package command-line-arguments: cannot find package "command-line-arguments" in any of:
        C:\Go\src\command-line-arguments (from $GOROOT)
        E:\go\src\command-line-arguments (from $GOPATH)

--> linux/arm error: exit status 1
Stderr: can't load package: package command-line-arguments: cannot find package "command-line-arguments" in any of:
        C:\Go\src\command-line-arguments (from $GOROOT)
        E:\go\src\command-line-arguments (from $GOPATH)

--> darwin/386 error: exit status 1
Stderr: can't load package: package command-line-arguments: cannot find package "command-line-arguments" in any of:
        C:\Go\src\command-line-arguments (from $GOROOT)
        E:\go\src\command-line-arguments (from $GOPATH)

--> linux/386 error: exit status 1
Stderr: can't load package: package command-line-arguments: cannot find package "command-line-arguments" in any of:
        C:\Go\src\command-line-arguments (from $GOROOT)
        E:\go\src\command-line-arguments (from $GOPATH)

--> linux/amd64 error: exit status 1
Stderr: can't load package: package command-line-arguments: cannot find package "command-line-arguments" in any of:
        C:\Go\src\command-line-arguments (from $GOROOT)
        E:\go\src\command-line-arguments (from $GOPATH)

--> freebsd/386 error: exit status 1
Stderr: can't load package: package command-line-arguments: cannot find package "command-line-arguments" in any of:
        C:\Go\src\command-line-arguments (from $GOROOT)
        E:\go\src\command-line-arguments (from $GOPATH)

--> openbsd/amd64 error: exit status 1
Stderr: can't load package: package command-line-arguments: cannot find package "command-line-arguments" in any of:
        C:\Go\src\command-line-arguments (from $GOROOT)
        E:\go\src\command-line-arguments (from $GOPATH)

--> openbsd/386 error: exit status 1
Stderr: can't load package: package command-line-arguments: cannot find package "command-line-arguments" in any of:
        C:\Go\src\command-line-arguments (from $GOROOT)
        E:\go\src\command-line-arguments (from $GOPATH)

--> windows/386 error: exit status 1
Stderr: can't load package: package command-line-arguments: cannot find package "command-line-arguments" in any of:
        C:\Go\src\command-line-arguments (from $GOROOT)
        E:\go\src\command-line-arguments (from $GOPATH)

--> windows/amd64 error: exit status 1
Stderr: can't load package: package command-line-arguments: cannot find package "command-line-arguments" in any of:
        C:\Go\src\command-line-arguments (from $GOROOT)
        E:\go\src\command-line-arguments (from $GOPATH)

--> freebsd/arm error: exit status 1
Stderr: can't load package: package command-line-arguments: cannot find package "command-line-arguments" in any of:
        C:\Go\src\command-line-arguments (from $GOROOT)
        E:\go\src\command-line-arguments (from $GOPATH)

--> freebsd/amd64 error: exit status 1
Stderr: can't load package: package command-line-arguments: cannot find package "command-line-arguments" in any of:
        C:\Go\src\command-line-arguments (from $GOROOT)
        E:\go\src\command-line-arguments (from $GOPATH)

--> netbsd/386 error: exit status 1
Stderr: can't load package: package command-line-arguments: cannot find package "command-line-arguments" in any of:
        C:\Go\src\command-line-arguments (from $GOROOT)
        E:\go\src\command-line-arguments (from $GOPATH)

--> netbsd/amd64 error: exit status 1
Stderr: can't load package: package command-line-arguments: cannot find package "command-line-arguments" in any of:
        C:\Go\src\command-line-arguments (from $GOROOT)
        E:\go\src\command-line-arguments (from $GOPATH)

--> netbsd/arm error: exit status 1
Stderr: can't load package: package command-line-arguments: cannot find package "command-line-arguments" in any of:
        C:\Go\src\command-line-arguments (from $GOROOT)
        E:\go\src\command-line-arguments (from $GOPATH)

--> linux/s390x error: exit status 1
Stderr: can't load package: package command-line-arguments: cannot find package "command-line-arguments" in any of:
        C:\Go\src\command-line-arguments (from $GOROOT)
        E:\go\src\command-line-arguments (from $GOPATH)

--> linux/mips64 error: exit status 1
Stderr: can't load package: package command-line-arguments: cannot find package "command-line-arguments" in any of:
        C:\Go\src\command-line-arguments (from $GOROOT)
        E:\go\src\command-line-arguments (from $GOPATH)

--> linux/mips64le error: exit status 1
Stderr: can't load package: package command-line-arguments: cannot find package "command-line-arguments" in any of:
        C:\Go\src\command-line-arguments (from $GOROOT)
        E:\go\src\command-line-arguments (from $GOPATH)

--> linux/mipsle error: exit status 1
Stderr: can't load package: package command-line-arguments: cannot find package "command-line-arguments" in any of:
        C:\Go\src\command-line-arguments (from $GOROOT)
        E:\go\src\command-line-arguments (from $GOPATH)

--> linux/mips error: exit status 1
Stderr: can't load package: package command-line-arguments: cannot find package "command-line-arguments" in any of:
        C:\Go\src\command-line-arguments (from $GOROOT)
        E:\go\src\command-line-arguments (from $GOPATH)

**Comment by alex595555** [comment]
I am having too the error
i use go on the ram drive i set GOROOT GOPATH to this ramdrive, what else?
