### ISSUE TITLE
Could you please add arm64 for extra option for arm64?

### ISSUE THREAD

**Issue by SuzukiHonoka** [mitchellh/gox#144]
The 32 bit arm support now are not widely used by Linux programmer although we could simply switch to arm64. 
Please consider to add arm64 as a extra option.
Thanks!

**Comment by robertpeteuil** [comment]
You can compile for `linux/arm64` using the `-osarch=` parameter.

Here's the full command: `gox -osarch="linux/arm64"`

**Comment by SuzukiHonoka** [comment]
> You can compile for `linux/arm64` using the `-osarch=` parameter.
> 
> Here's the full command: `gox -osarch="linux/arm64"`

thank you
