### ISSUE TITLE
Any idea of what might be happening here?

### ISSUE THREAD

**Issue by c4milo** [mitchellh/gox#15]
The source is there, so I don't really understand where the error is stemming from. I'm using Go 1.3 which supposedly already support cross compiling CGO. 

```shell
--> freebsd/arm error: exit status 1
Stderr: go build github.com/libgit2/git2go: no buildable Go source files in /Users/camilo/Dropbox/Development/go/src/github.com/libgit2/git2go
```

**Comment by jszwedko** [comment]
@c4milo did you specify the `-cgo` flag?

**Comment by c4milo** [comment]
This was more than a year ago. I'm closing it since it is not longer relevant.

**Comment by jszwedko** [comment]
:) I saw that, but stumbled upon it after hitting the same issue so I figured I'd respond anyway.

**Comment by c4milo** [comment]
ha! thanks for that @jszwedko.
