### ISSUE TITLE
cgo darwin -> linux/amd64 fails

### ISSUE THREAD

**Issue by pquerna** [mitchellh/gox#23]
Using go1.3, cross compiling to Linux/amd64, I get a failure compiling sqlite3.  Easy example case bellow:

```
gox -verbose -osarch linux/amd64 github.com/mattn/go-sqlite3/_example/simple
Number of parallel builds: 4

-->     linux/amd64: github.com/mattn/go-sqlite3/_example/simple

1 errors occurred:
--> linux/amd64 error: exit status 2
Stderr: # github.com/mattn/go-sqlite3
../github.com/mattn/go-sqlite3/sqlite3.c:92 unknown #: if
../github.com/mattn/go-sqlite3/sqlite3.c:94 6c: No such file or directory: mingw.h
```

Is this an expected failure?

From what I can find, this would be expected to work with Go 1.3:
https://code.google.com/p/go/issues/detail?id=4714

**Comment by cpjolicoeur** [comment]
+1 for this.  Would be great to this working if possible and past the linker step

```
> CGO_ENABLED=1 gox -osarch="linux/amd64"                                  
Number of parallel builds: 4

-->     linux/amd64: _/src/se-editor/server

1 errors occurred:
--> linux/amd64 error: exit status 2
Stderr: # runtime/cgo
ld: unknown option: --build-id=none
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by ian-kent** [comment]
:+1:

We've had similar issues cross-compiling [go-tiff2pdf](https://github.com/companieshouse/go-tiff2pdf) from darwin to linux/amd64 - resorted to building inside a docker container which feels hacky, and doesn't play nice with travis

**Comment by desimone** [comment]
:+1:

**Comment by mitchellh** [comment]
Supported with `-cgo` flag
