### ISSUE TITLE
GOX Refuses to Build Solaris Binaries

### ISSUE THREAD

**Issue by tychoish** [mitchellh/gox#33]
I specify solaris and get the following error: 

```
$ gox --osarch="solaris/amd64"         
No valid platforms to build for. If you specified a value
for the 'os', 'arch', or 'osarch' flags, make sure you're
using a valid value.
```

When I run `gox` without specifying an operating system it does not run solaris builds. Running on an Arch Linux system with the following version: 

```
go version go1.4.2 linux/amd64
```

**Comment by mitchellh** [comment]
Fixed
