### ISSUE TITLE
gox windows not builds

### ISSUE THREAD

**Issue by MasterDimmy** [mitchellh/gox#42]
C:/sync-folders/dk_sync/Projects/Sugarbowl/src/webstat>gox
Stderr:
--> netbsd/arm error: chdir _C_/sync-folders/dk_sync/Projects/Sugarbowl/src/webstat: The filename, directory name, or volume label syntax is incorrect.
Stderr:
--> plan9/386 error: chdir _C_/sync-folders/dk_sync/Projects/Sugarbowl/src/webstat: The filename, directory name, or volume label syntax is incorrect.

I fix this with following:

file "go.go" line 58
just set to this: 
		chdir = packagePath[2:3] + ":" + packagePath[4:]

then rebuild gox

And All ok now:
C:/sync-folders/dk_sync/Projects/Sugarbowl/src/webstat>gox
Number of parallel builds: 8

-->      darwin/386: _/C_/sync-folders/dk_sync/Projects/Sugarbowl/src/webstat
-->    darwin/amd64: _/C_/sync-folders/dk_sync/Projects/Sugarbowl/src/webstat
-->       linux/386: _/C_/sync-folders/dk_sync/Projects/Sugarbowl/src/webstat
-->     linux/amd64: _/C_/sync-folders/dk_sync/Projects/Sugarbowl/src/webstat
-->       linux/arm: _/C_/sync-folders/dk_sync/Projects/Sugarbowl/src/webstat
-->     freebsd/386: _/C_/sync-folders/dk_sync/Projects/Sugarbowl/src/webstat
-->   freebsd/amd64: _/C_/sync-folders/dk_sync/Projects/Sugarbowl/src/webstat
-->     openbsd/386: _/C_/sync-folders/dk_sync/Projects/Sugarbowl/src/webstat
-->   openbsd/amd64: _/C_/sync-folders/dk_sync/Projects/Sugarbowl/src/webstat
-->     windows/386: _/C_/sync-folders/dk_sync/Projects/Sugarbowl/src/webstat
-->   windows/amd64: _/C_/sync-folders/dk_sync/Projects/Sugarbowl/src/webstat
-->     freebsd/arm: _/C_/sync-folders/dk_sync/Projects/Sugarbowl/src/webstat
-->      netbsd/386: _/C_/sync-folders/dk_sync/Projects/Sugarbowl/src/webstat
-->    netbsd/amd64: _/C_/sync-folders/dk_sync/Projects/Sugarbowl/src/webstat
-->      netbsd/arm: _/C_/sync-folders/dk_sync/Projects/Sugarbowl/src/webstat
-->       plan9/386: _/C_/sync-folders/dk_sync/Projects/Sugarbowl/src/webstat

**Comment by mitchellh** [comment]
This is fixed.
