### ISSUE TITLE
What is go_test.go used for?

### ISSUE THREAD

**Issue by stapelberg** [mitchellh/gox#47]
As evidenced by e.g. commit https://github.com/mitchellh/gox/commit/733261c, go_test.go needs to be updated for each Go release.

I don’t see the value which go_test.go provides. What is it useful for?

Can’t we just delete it and avoid having to update it whenever there’s a new Go release?

**Comment by mitchellh** [comment]
It is used to test that the Go version checking works. Since it executes your system Go version, we just have to keep it updated with a list of acceptable values. There aren't a lot of Go releases so updating it isn't a big burden.

We'd like some test there to verify parsing works. If you imagine a scenario where a future Go version changes the output format, we'd catch it this way.

**Comment by stapelberg** [comment]
> We'd like some test there to verify parsing works. If you imagine a scenario where a future Go version changes the output format, we'd catch it this way.

Are you talking about the Go version being in the format of go1.<x>[.<y>]? If yes, why do you need to use hard-coded values for this instead of using a regexp to verify it matches your expectation?

(For context: we’re packaging gox for Debian, and the currently released version does not contain commit https://github.com/mitchellh/gox/commit/733261c yet, so its test suite fails.)

**Comment by mitchellh** [comment]
@stapelberg No, I mean the actual stdout/stderr format of `go version`. Gox is actually subprocessing out to Go to inspect your build environment.

**Comment by stapelberg** [comment]
Okay. So, why is the following test not an acceptable replacement?

```go
out, err := exec.Command("go", "version").Output()
if err != nil {
    t.Fatalf("Could not run 'go version': %v", err)
}
re := regexp.MustCompile(`go version go\d+\.\d+ (.+)`)
matches := re.FindStringSubmatch(string(out))
if len(matches) != 2 {
    t.Fatalf("Unexpected 'go version' output: got %d, want %q", len(matches), 2)
}
```

**Comment by mitchellh** [comment]
Something like that would probably be great!

**Comment by stapelberg** [comment]
Thanks. Do you want to implement it yourself or should I send a pull request?
