### ISSUE TITLE
Enabling CGO for native builds

### ISSUE THREAD

**Issue by leonsodhi** [mitchellh/gox#49]
I could easily be missing something here so please feel free to correct me, but it seems as though CGO should be enabled when building a binary for the platform you're running on even if `CGO_ENABLED` hasn't been set. This behaviour would then line up with Go's own build tool ([source](https://github.com/golang/go/blob/a7d331b368cb4f16db7bc1919a82af878e382ba4/src/go/build/build.go#L308-L314)).

**Comment by danesparza** [comment]
Isn't that issue addressed [here](https://github.com/mitchellh/gox/issues/23#issuecomment-113169323)?

**Comment by leonsodhi** [comment]
Sort of. [This](https://github.com/papertrail/remote_syslog2/blob/master/Makefile#L24-L25) is the Makefile I'm working with, and you can see that the `-cgo` flag has been specified for each platform. The problem is that compiling a Linux build on OS X will result in the final binary depending on OS X libs, and thus it fails to execute. If I don't specify `-cgo`, the built Linux binary works fine but the darwin build fails as it makes use of a C lib.

Given that there's no harm (at least, AFAIK) in allowing the use of C libraries when you're building for the platform that you're running on, `-cgo` shouldn't be needed and nor should `CGO_ENABLED`. This seems to be the way Go's own build tool works, and you can see that reflected in [this](https://github.com/golang/go/blob/a7d331b368cb4f16db7bc1919a82af878e382ba4/src/go/build/build.go#L308-L314) comment:

> // cgo must be explicitly enabled for cross compilation builds

**Comment by mitchellh** [comment]
This makes sense to me. Done.

**Comment by leonsodhi** [comment]
Thanks @mitchellh!

**Comment by errm** [comment]
This seems to have broken builds for different architectures on the same platform...

e.g. https://travis-ci.org/containous/traefik/builds/127956964

**Comment by danesparza** [comment]
I have to agree with @errm.  I'm not sure why, but this breaks the linux 386 and ARM builds when running on my CircleCI controller.  No other platforms seem to be affected.  I forked the code, rolled back just this change, and used the forked version of gox and it seems to work just fine.  :confounded:

**Comment by mitchellh** [comment]
Ouch I tested this on my own builds with cgo and it worked but let me add the arch check too!

**Comment by mitchellh** [comment]
Done, please let me know if that helps.

**Comment by danesparza** [comment]
@mitchellh Works for me again now.  Thanks for the fix!
