### ISSUE TITLE
Local platform build is dynamic but all others are static

### ISSUE THREAD

**Issue by ncw** [mitchellh/gox#55]
Eg from a recent build of rclone you can see that all these are static builds, except for the linux/amd64 build which is the platform I build on.

This seems inconsistent!

 * freebsd-386:   ELF 32-bit LSB executable, Intel 80386, version 1 (FreeBSD), *statically* linked, not stripped
 * freebsd-amd64: ELF 64-bit LSB executable, x86-64, version 1 (FreeBSD), *statically* linked, not stripped
 * freebsd-arm:   ELF 32-bit LSB executable, ARM, EABI5 version 1 (FreeBSD), *statically* linked, not stripped
 * linux-386:     ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), *statically* linked, not stripped
 * linux-amd64:   ELF 64-bit LSB executable, x86-64, version 1 (SYSV), **dynamically** linked, interpreter /lib64/ld-linux-x86-64.so.2, not stripped
 * linux-arm:     ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), *statically* linked, not stripped
 * netbsd-386:    ELF 32-bit LSB executable, Intel 80386, version 1 (NetBSD), *statically* linked, for NetBSD 5.99, not stripped
 * netbsd-amd64:  ELF 64-bit LSB executable, x86-64, version 1 (NetBSD), *statically* linked, for NetBSD 5.99, not stripped
 * netbsd-arm:    ELF 32-bit LSB executable, ARM, version 1 (NetBSD), *statically* linked, for NetBSD 5.99, not stripped
 * openbsd-386:   ELF 32-bit LSB executable, Intel 80386, version 1 (OpenBSD), *statically* linked, for OpenBSD, not stripped
 * openbsd-amd64: ELF 64-bit LSB executable, x86-64, version 1 (OpenBSD), *statically* linked, for OpenBSD, not stripped

**Comment by mitchellh** [comment]
We're just calling `go build` with no additional flags. We export flags such as ldflags so you can customize this and probably unify the behavior. I don't think Gox should try to be clever here, it just forwards along commands and parallelizes.

**Comment by docwhat** [comment]
Just for others that find this issue.  Assuming your compilation doesn't have problems with being statically compiled, then just setting the environment variable `CGO_ENABLED=0` will make all binaries, including the native one, static.  I tested this on go 1.5 and 1.6.  I assume the behavior won't change for a while.

Example:

``` sh
$ env CGO_ENABLED=0 gox -os='linux darwin' -arch='amd64 ppc64le' ./...
```

**Comment by ncw** [comment]
@docwhat yes that was the eventual solution I came up with for rclone too.

**Comment by docwhat** [comment]
Is there a reason not to force set that variable in `gox` itself? I would expect the binaries from `gox`, given the same versions of go, would be the same whether I built from OS  X, Linux or Windows.

When the results are different (e.g. the native binary is dynamic) it makes trouble shooting problems difficult.
