### ISSUE TITLE
Output in uname format?

### ISSUE THREAD

**Issue by caarlos0** [mitchellh/gox#56]
Is there any way to set the `--output` to something like `./bin/{{.Dir}}_{{uname -s}}_{{.uname -m}}`?

I'm currently using `.OS` and `.ARCH`, but it is not in the `uname` format...

**Comment by mitchellh** [comment]
There isn't, and I think we should keep `output` simple. I recommend using `output` with a sentinel value like `UNAME_S` (literally) and then using a script to replace those. I normally see Gox scripted anyways so I think this is better than arbitrary complexity to the output format.
