### ISSUE TITLE
New tag?

### ISSUE THREAD

**Issue by ilovezfs** [mitchellh/gox#66]
I was looking into making a Homebrew formula for this, but noticed that the most recent tag is quite a bit older than HEAD, and Homebrew only distributes tagged releases. Any chance of getting a new tag?

**Comment by ilovezfs** [comment]
@mitchellh FYI https://github.com/Homebrew/homebrew-core/pull/1982

**Comment by ilovezfs** [comment]
bump

**Comment by sgerrand** [comment]
👋  @mitchellh: Any chance of tagging the HEAD of master? It's been static for a year now.

**Comment by ilovezfs** [comment]
@mitchellh ping. It would be great to have a new tag :)

**Comment by mattfarina** [comment]
Done. https://github.com/mitchellh/gox/releases/tag/v0.4.0

**Comment by ilovezfs** [comment]
Thanks @mattfarina! Voilà: https://github.com/Homebrew/homebrew-core/pull/22005
