### ISSUE TITLE
Failing to Build in cmd/...

### ISSUE THREAD

**Issue by elithrar** [mitchellh/gox#74]
Attempting to use gox to cross-compile binaries, where the root of the package is a library, and package main is in `cmd/logshare-cli` (usual convention).

Seeing the below instead:
```
~/.go/src/github.com/cloudflare/logshare(master ✔) gox -os="linux darwin windows" -arch="amd64" -output="logshare.{{.OS}}.{{.Arch}}" ./...
Number of parallel builds: 7

-->   windows/amd64: github.com/cloudflare/logshare/cmd/logshare-cli
-->     linux/amd64: github.com/cloudflare/logshare/cmd/logshare-cli
-->    darwin/amd64: github.com/cloudflare/logshare/cmd/logshare-cli

3 errors occurred:
--> darwin/amd64 error: exit status 1
Stderr: cmd/logshare-cli/main.go:9:2: no buildable Go source files in /Users/matt/.go/src/github.com/cloudflare/logshare

--> linux/amd64 error: exit status 1
Stderr: cmd/logshare-cli/main.go:9:2: no buildable Go source files in /Users/matt/.go/src/github.com/cloudflare/logshare

--> windows/amd64 error: exit status 1
Stderr: cmd/logshare-cli/main.go:9:2: no buildable Go source files in /Users/matt/.go/src/github.com/cloudflare/logshare
```

Running from within `cmd/logshare-cli` or specifying the fully-qualified package path (github.com/cloudflare/logshare/cmd/logshare-cli) still fails with the same error: gox can't seem to see past the library.

**Comment by n3integration** [comment]
Although this issue is almost a year old, I ran into the same issue when building a project with a similar project layout. The solution was to add the package name(s) to the end of the command. For example:

`gox -os="linux darwin windows" -arch="amd64" -output="logshare.{{.OS}}.{{.Arch}}" cmd/logshare-cli`
