### ISSUE TITLE
Exclusion flags

### ISSUE THREAD

**Issue by mcandre** [mitchellh/gox#81]
Could gox get some flags like `--exclude-os='linux windows darwin'`, `--exclude-arch='arm arm64'`? That way, users can tell gox what *not* to build, rather than explicitly listing what it should build.

**Comment by Greg-Szabo** [comment]
Do you mean like the `!` in  the `-os`, `-arch` and `-osarch` flags? (Maybe this is just an old issue that was not closed.)

For example this will build windows and solaris binaries only, but not for the ARM platform:
```
gox -os='!linux !darwin' -arch='!arm !arm64'
```

From the help:```
  The operating systems and architectures to cross-compile for may be
  specified with the "-arch" and "-os" flags. These are space separated lists
  of valid GOOS/GOARCH values to build for, respectively. You may prefix an
  OS or Arch with "!" to negate and not build for that platform. If the list
  is made up of only negations, then the negations will come from the default
  list.
```

I think this can be closed.

**Comment by mattfarina** [comment]
Closing because this works via the `!` prefix on a platform.
