### ISSUE TITLE
CLA for gox

### ISSUE THREAD

**Issue by Nayana-ibm** [mitchellh/gox#86]
Hi,
To contribute for changes in gox, we want to know about Contributor License Agreement.

Please let us know which Contributor License Agreement needs for gox.
I have checked URL to License: https://github.com/franciscocpg/gox/blob/master/LICENSE and
https://github.com/mitchellh/gox/blob/master/LICENSE however what's the CLA gox requires?

**Comment by Nayana-ibm** [comment]
@mitchellh @franciscocpg Could you please provide your inputs?

**Comment by mattfarina** [comment]
@Nayana-ibm There is no note of a requirement for a CLA here and Mitchell hasn't responded on a need for one. Like most projects on GitHub I would assume there's no CLA requirement.

You can either close this if they answer is sufficient or I can close it on my next pass.
