### ISSUE TITLE
Continuation of gox project

### ISSUE THREAD

**Issue by ruflin** [mitchellh/gox#93]
The `gox` project is of great use for us and I would love to see this project further developed with support for additional platforms which were added to Golang. There haven't been much changes in the last year but based on the forks and open PR's there seems to be interest from the community. Looking at the forks of the projects (https://github.com/mitchellh/gox/network) a few forks have integrated open PR's for their own needs I assume.

Instead of having the changes in different places I would love to see this project moving forward in one place. My preferred option would be in this repository here or a "blessed" fork form @mitchellh . @mitchellh could you share your thoughts on the future of this project? Thanks a lot for all the work you put into this so far.

Mentioning @mattfarina @dave-tucker @roscopecoltran @AlexHaber here as I see you guys forked and changed the project very recently and curious to here your thoughts.

**Comment by dave-tucker** [comment]
@ruflin I forked `gox` so I could add support for building `packer` on some other architectures (mainly `s390x` and `ppc64le`). Support in `packer` upstream would require my changes to be merged here + a PR to `packer` to enable them. I'm willing to make that contribution... but the fact that there are already many open PR's here that effectively make the same change ihas put me off.

My £0.02 is that if this is to be used in active upstream projects like `packer` then it should be maintained and if not, it should be replaced.

(NOTE: This comment is not intended to be inflammatory 🔥) Other than my need for `packer` on weird architectures I don't use `gox`. I'm quite happy with `make` and adjusting the `GOOS` and `GOARCH` myself. This isn't for everyone though, so if people are using it and are happy with it, then that's cool 😎

**Comment by mattfarina** [comment]
Hey folks, having been using a fork of gox myself for some time Mitchell gave me write access here. In the next few weeks I'll be going through everything and seeing what I can do to get this going again.

**Comment by ruflin** [comment]
@mattfarina That is great news. Anything we can help here?

@dave-tucker In our case for beats (https://github.com/elastic/beats)  we only use `gox` without packer and are pretty happy. We could do the same with some shell scripts probably but we would just reinvent what gox does.

**Comment by mattfarina** [comment]
@ruflin One of the first things I'd like is to get the tests passing again and to get Travis CI and AppVeyor setup. Then I'll be a little more confident in what's merged going forward.

**Comment by ruflin** [comment]
@mattfarina I wonder if we should start with a very quick fix for the tests as I did here: https://github.com/mitchellh/gox/compare/master...ruflin:quick-test-fix?expand=1 This brings the test back to green (for go1.9.2) and it allows us to do follow up PR's adding all the definitions for the golang versions matching the platforms instead of doing it all at once.

In general I wonder how far back older Golang versions should be supported.

**Comment by mattfarina** [comment]
@ruflin Can you see #94. Note, appveyor is failing (windows testing) but I hope to set that up separately.

**Comment by ruflin** [comment]
@mattfarina Yep, great stuff. Just left a minor comment.

**Comment by ruflin** [comment]
@mattfarina From my perspective we can close this issue as I'm seeing the project is moving forward again which is awesome. Thanks for taking this up.
